// Code generated by mockery v1.0.0. DO NOT EDIT.

package models

import mock "github.com/stretchr/testify/mock"

// MockPatron is an autogenerated mock type for the Patron type
type MockPatron struct {
	mock.Mock
}
